[workspace]
members = [
    "common",
    "tensor",
    "tokenizer",
    "causal-lm",
    "sample",
    "service",
    "web-api",
    "xtask",

    "devices/common",
    "devices/common-cpu",
    "devices/nvidia-gpu",
    "devices/cambricon-mlu",

    "models/llama/common",
    "models/llama/common-cpu",
    "models/llama/nvidia-gpu",
    "models/llama/nvidia-gpu-distributed",
    "models/llama/cambricon-mlu",
    "models/mixtral/common",
    "models/mixtral/cpu",
]
resolver = "2"

[workspace.dependencies]
half = "2.4"
log = "0.4"
itertools = "0.13"
serde = "1.0"
serde_json = "1.0"
memmap2 = "0.9"
rayon = "1.10"
tokio = { version = "1.38", features = ["rt-multi-thread", "sync"] }
build-script-cfg = "0.0"

operators = { git = "https://github.com/YdrMaster/operators-rs", rev = "015f283", default-features = false }

cuda = { git = "https://github.com/YdrMaster/cuda-driver", rev = "62a7864" }
nccl = { git = "https://github.com/YdrMaster/cuda-driver", rev = "62a7864" }
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "62a7864" }

cndrv = "0.0"
search-neuware-tools = "0.0"
