[workspace]
members = [
    "common",
    "tensor",
    "tokenizer",
    "causal-lm",
    "sample",
    "kernel-lib",
    "service",
    "web-api",
    "xtask",

    "devices/cpu",
    "devices/nvidia",

    "models/llama/common",
    "models/llama/cpu",
    "models/llama/nvidia",
    "models/llama/nvidia-distributed",
]
resolver = "2"

[workspace.dependencies]
half = "2.4"
log = "0.4"
itertools = "0.12"
serde = "1.0"
serde_json = "1.0"
memmap2 = "0.9"
rayon = "1.10"
tokio = { version = "1.37", features = ["rt-multi-thread", "sync"] }

cuda = { git = "https://github.com/YdrMaster/cuda-driver", rev = "c47aed2" }
cublas = { git = "https://github.com/YdrMaster/cuda-driver", rev = "c47aed2" }
nccl = { git = "https://github.com/YdrMaster/cuda-driver", rev = "c47aed2" }
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "c47aed2" }
