[workspace]
members = [
    "common",
    "tensor",
    "tokenizer",
    "transformer",
    "transformer-cpu",
    "nvidia/common",
    "nvidia/transformer",
    "nvidia/distributed",
    "service",
    "xtask",
]
resolver = "2"

[workspace.dependencies]
half = "2.4"
rayon = "1.9"
serde_json = "1.0"
serde = "1.0"
log = "0.4"
tokio = { version = "1.37", features = ["rt-multi-thread", "sync"] }

cuda = { git = "https://github.com/YdrMaster/cuda-driver", rev = "e95b84" }
cublas = { git = "https://github.com/YdrMaster/cuda-driver", rev = "e95b84" }
nccl = { git = "https://github.com/YdrMaster/cuda-driver", rev = "e95b84" }
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "e95b84" }
