[workspace]
members = [
    "common",
    "tensor",
    "tokenizer",
    "causal-lm",
    "sample",
    "kernel-lib",
    "models/llama",
    "transformer-cpu",
    "nvidia/common",
    "nvidia/transformer",
    "nvidia/distributed",
    "service",
    "web-api",
    "xtask",
]
resolver = "2"

[workspace.dependencies]
half = "2.4"
log = "0.4"
itertools = "0.12"
serde = "1.0"
serde_json = "1.0"
memmap2 = "0.9"
rayon = "1.10"
tokio = { version = "1.37", features = ["rt-multi-thread", "sync"] }

cuda = { git = "https://github.com/YdrMaster/cuda-driver", rev = "9ca78ac" }
cublas = { git = "https://github.com/YdrMaster/cuda-driver", rev = "9ca78ac" }
nccl = { git = "https://github.com/YdrMaster/cuda-driver", rev = "9ca78ac" }
search-cuda-tools = { git = "https://github.com/YdrMaster/cuda-driver", rev = "9ca78ac" }
