[workspace]
members = [
    "common",
    "tensor",
    "tokenizer",
    "transformer",
    "transformer-cpu",
    "transformer-nvidia",
    "service",
    "xtask",
]
resolver = "2"

[workspace.dependencies]
find_cuda_helper = "0.2"
half = "2.4"
serde_json = "1.0"
serde = "1.0"
log = "0.4"
