[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
tensor = { path = "../tensor" }
tokenizer = { path = "../tokenizer" }
transformer-cpu = { path = "../transformer-cpu" }
transformer-nvidia = { path = "../transformer-nvidia" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
log = "0.4"
simple_logger = "4.3"
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
find_cuda_helper.workspace = true
