[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokenizer = { path = "../tokenizer" }
transformer-cpu = { path = "../transformer-cpu" }
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5", features = ["derive"] }
