[package]
name = "service"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
tokenizer = { path = "../tokenizer" }
log.workspace = true
tokio = { version = "1.36", features = ["rt", "sync"] }
