[package]
name = "tensor"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.4"
smallvec = "1.13"
nalgebra = "0.32"
rayon = "1.8"
serde = "1.0"
