[package]
name = "web-handler"
version = "0.0.1"
edition = "2021"
authors = ["Zezhong Pan <panzezhong@qiyuanlab.com>"]

[dependencies]
actix-web = "*"
futures = "*"
tokio = "*"
serde = { version = "*", features = ["derive"] }
transformer = { path = "../transformer" }
service = { path = "../service" }
